const PERMISSIONS = require("./permissions");

const ROLES = {
  CITIZEN: "CITIZEN",
  OFFICER: "OFFICER",
  ADMIN: "ADMIN",
};

const ROLE_PERMISSIONS = {
  [ROLES.CITIZEN]: [
    PERMISSIONS.COMPLAINT_CREATE,
    PERMISSIONS.COMPLAINT_READ_OWN,
  ],

  [ROLES.OFFICER]: [
    PERMISSIONS.COMPLAINT_READ_DEPARTMENT,
    PERMISSIONS.COMPLAINT_UPDATE_STATUS,
    PERMISSIONS.COPILOT_QUERY,
    PERMISSIONS.RECOMMENDATION_DECIDE,
  ],

  [ROLES.ADMIN]: [
    PERMISSIONS.COMPLAINT_READ_DEPARTMENT,
    PERMISSIONS.COMPLAINT_UPDATE_STATUS,
    PERMISSIONS.OFFICER_MANAGE,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.COPILOT_QUERY,
    PERMISSIONS.RECOMMENDATION_DECIDE,
    PERMISSIONS.AUDIT_READ,
  ],
};

module.exports = {
  ROLES,
  ROLE_PERMISSIONS,
};